version: '3'

services:
  db:
    user: "1000"
    image: mysql:5.6
    volumes:
      - ./docker/lib/mysql:/var/lib/mysql
      - ./docker/dumps:/docker-entrypoint-initdb.d
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: application
      MYSQL_DATABASE: application
      MYSQL_USER: application
      MYSQL_PASSWORD: application
    ports:
      - "3305:3306"
  application:
    user: "1000"
    depends_on:
      - db
      - php
    image: nginx:latest
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8088:8088
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_PASSWORD: application
  php:
    user: "1000"
    image: miron/php7-custom:latest
    restart: always
    environment:
      XDEBUG_CONFIG: remote_port=9002 remote_connect_back=1 idekey=PHPSTORM remote_host=172.17.0.1 remote_enable=1 idekey=PHPSTORM
    expose:
      - "9000"
    ports:
      - "9002:9002"
    volumes:
      - ./:/var/www/html
